### ISSUE TITLE
syntax error in savejdf

### ISSUE THREAD

**Issue by Mirage10** [xiaodaigh/JDF.jl#28]
first of all: JDF is a great package. well done. unfortunately I get an syntax error for the example mentioned in the github:
using VegaDatasets, JDF, DataFrames

a = dataset("iris") |> DataFrame
@time metadatas = savejdf("iris.jdf", a)
@time a2 = loadjdf("iris.jdf")

here savejdf raises an syntax error:

ERROR: MethodError: no method matching getindex(::DataFrame, ::typeof(!), ::Int64)
Closest candidates are:
  getindex(::DataFrame, ::Integer, ::Union{Signed, Unsigned}) at /home/user/.julia/packages/DataFrames/0Em9Q/src/dataframe/dataframe.jl:311
  getindex(::DataFrame, ::AbstractArray{T,1} where T, ::Union{Signed, Symbol, Unsigned}) at /home/user/.julia/packages/DataFrames/0Em9Q/src/dataframe/dataframe.jl:337
  getindex(::DataFrame, ::Colon, ::Union{Signed, Symbol, Unsigned}) at /home/user/.julia/packages/DataFrames/0Em9Q/src/dataframe/dataframe.jl:358
  ...
Stacktrace:
 [1] ssavejdf(::String, ::DataFrame) at /home/user/.julia/packages/JDF/Saot5/src/JDF.jl:105
 [2] savejdf(::String, ::DataFrame) at /home/user/.julia/packages/JDF/Saot5/src/JDF.jl:57
 [3] top-level scope at util.jl:156

on julia 1.2 as well as on julia 1.4

hope this info helps for further optimizing JDF

best regards from Germany

**Comment by xiaodaigh** [comment]
Looks like you are using old version of DataFrames. Please upgrade to latest version of JDF

**Comment by xiaodaigh** [comment]
Pretty sure you are using a really old version of JDF because the syntax tells me you are using DataFrames.jl older than 0.19.x

Please use a new environment and install the latest versions to test e.g.

```
]activate test-env
add DataFrames JDF VegaDatasets
```
then
```julia
using VegaDatasets, JDF, DataFrames

a = dataset("iris") |> DataFrame
@time metadatas = savejdf("iris.jdf", a)
@time a2 = loadjdf("iris.jdf")
```

**Comment by Mirage10** [comment]
cool! an julia 1.4 everything is fine. But on julia 1.2 the syntax error still perists. even tough I added the latest DataFrame package.  Maybe there is something not consistent.  Have a great day ahead and thank you for this ultra fast approach!!!

**Comment by xiaodaigh** [comment]
@Mirage10 

On Julia 1.2 can you show me the 

```
versioninfo()
```

and 

```
]st
```
?
