### ISSUE TITLE
type_compress

### ISSUE THREAD

**Issue by matthieugomez** [xiaodaigh/JDF.jl#3]
- maybe you could rename `type_compress` to `compress` (and imports it from `CategoricalVector`).
- Maybe you could compress strings to PooledDataVector, not CategoricalVector (which requires a very different syntax).

**Comment by xiaodaigh** [comment]
Thank you for your suggedtions

**Comment by xiaodaigh** [comment]
> * Maybe you could compress strings to PooledDataVector, not CategoricalVector (which requires a very different syntax).

Even the official docs don't mention PooledDataVector and only mentions CategoricalVetors.

**Comment by xiaodaigh** [comment]
> * `type_compress` to `compress`

It's `type_compress!` and I think there might be other uses of `compress` later on for DataFrames, so I will leave it at `type_compress!`

**Comment by matthieugomez** [comment]
Which official docs?

**Comment by xiaodaigh** [comment]
See latest http://juliadata.github.io/DataFrames.jl/latest/man/categorical/

Versus in DataFrames.jl v0.9 http://juliadata.github.io/DataFrames.jl/v0.9.0/man/pooling/

**Comment by matthieugomez** [comment]
See
https://github.com/JuliaData/CategoricalArrays.jl/issues/151#issuecomment-402252366

**Comment by xiaodaigh** [comment]
What am I meant to see? A high-level description please?
