### ISSUE TITLE
Add support for DataFrames.jl v 0.21.0

### ISSUE THREAD

**Issue by bkamins** [xiaodaigh/JDF.jl#40]
Hi,

Can you consider adding support for DataFrames.jl v0.21.0 in JDF.jl? Thank you!

**Comment by xiaodaigh** [comment]
Yeah last time I checked it was blocked by CSV, try again.

**Comment by xiaodaigh** [comment]
Testing now seems to need to fix something. I will look at it now.

**Comment by xiaodaigh** [comment]
Done see https://github.com/JuliaRegistries/General/pull/14252

If you are rerunning the tutorial, can you please merge this PR first? https://github.com/bkamins/Julia-DataFrames-Tutorial/pull/21

**Comment by bkamins** [comment]
Fantastic. So I am left with Feather.jl to finish things!
