### ISSUE TITLE
Sync with DataFrames.jl 0.22

### ISSUE THREAD

**Issue by bkamins** [xiaodaigh/JDF.jl#52]
Can you please check if JDF.jl works with DataFrames.jl master (soon 0.22)?
It e.g. seems that you rely on DataFrames.jl re-exporting `CategoricalVector` which it does not any more.
Thank you!

**Comment by xiaodaigh** [comment]
updated latest master to work with DataFrames.jl v0.22.

tested to work. Imported CategoricalArray stuff directly.

**Comment by bkamins** [comment]
Thank you!

**Comment by bkamins** [comment]
Any success with registering the release?

**Comment by xiaodaigh** [comment]
done
