### ISSUE TITLE
Read a JDFFile in chunks

### ISSUE THREAD

**Issue by gcalderone** [xiaodaigh/JDF.jl#70]
Is it possible (or will someday be possible) to read a JDFFile in chunks?

I.e., something similar to:
```julia
df = DataFrame(JDF.load("iris.jdf", start=2, length=2))
```
to read just the 2nd and 3rd row.

Thanks!

**Comment by xiaodaigh** [comment]
Yeah. Might be possible. I am thinking through it. But for small ranges, it's not gonna be super efficient.
